spring:
    datasource:
        url: jdbc:h2:mem:client-db
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2
            settings.trace: false
            settings.web-allow-others: false